In [0]:
import pandas as pd

file_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/housing_processed_test.csv"

df = pd.read_csv(file_path)

print(df.shape)
print(df.columns.tolist())
df.head()

(133, 56)
['Name', 'URI', 'Region GSS code', 'Period', 'Sales volume', 'Reporting period', 'Average price All property types', 'Percentage change (yearly) All property types', 'Percentage change (monthly) All property types', 'House price index All property types', 'Sales volume All property types', 'Average price Detached houses', 'Percentage change (yearly) Detached houses', 'Percentage change (monthly) Detached houses', 'House price index Detached houses', 'Average price Semi-detached houses', 'Percentage change (yearly) Semi-detached houses', 'Percentage change (monthly) Semi-detached houses', 'House price index Semi-detached houses', 'Average price Terraced houses', 'Percentage change (yearly) Terraced houses', 'Percentage change (monthly) Terraced houses', 'House price index Terraced houses', 'Average price Flats and maisonettes', 'Percentage change (yearly) Flats and maisonettes', 'Percentage change (monthly) Flats and maisonettes', 'House price index Flats and maisonettes', 'Average price First-time buyers', 'Percentage change (yearly) First-time buyers', 'Percentage change (monthly) First-time buyers', 'House price index First-time buyers', 'Average price Former owner-occupiers', 'Percentage change (yearly) Former owner-occupiers', 'Percentage change (monthly) Former owner-occupiers', 'House price index Former owner-occupiers', 'Average price Cash purchases', 'Percentage change (yearly) Cash purchases', 'Percentage change (monthly) Cash purchases', 'House price index Cash purchases', 'Sales volume Cash purchases', 'Average price Mortgage purchases', 'Percentage change (yearly) Mortgage purchases', 'Percentage change (monthly) Mortgage purchases', 'House price index Mortgage purchases', 'Sales volume Mortgage purchases', 'Average price New build', 'Percentage change (yearly) New build', 'Percentage change (monthly) New build', 'House price index New build', 'Sales volume New build', 'Average price Existing properties', 'Percentage change (yearly) Existing properties', 'Percentage change (monthly) Existing properties', 'House price index Existing properties', 'Sales volume Existing properties', 'Pivotable date']

            Name  ... Pivotable date
0  East Midlands  ...     2015-01-01
1  East Midlands  ...     2015-02-01
2  East Midlands  ...     2015-03-01
3  East Midlands  ...     2015-04-01
4  East Midlands  ...     2015-05-01

[5 rows x 56 columns]

In [0]:
import re

def clean_column_name(col):
    col = col.strip().lower()
    col = col.replace('%', 'percent')
    col = re.sub(r'[^\w\s]', '', col)      # remove brackets and special chars
    col = re.sub(r'\s+', '_', col)         # spaces to underscores
    return col

df.columns = [clean_column_name(col) for col in df.columns]

print(df.columns.tolist())

['name', 'uri', 'region_gss_code', 'period', 'sales_volume', 'reporting_period', 'average_price_all_property_types', 'percentage_change_yearly_all_property_types', 'percentage_change_monthly_all_property_types', 'house_price_index_all_property_types', 'sales_volume_all_property_types', 'average_price_detached_houses', 'percentage_change_yearly_detached_houses', 'percentage_change_monthly_detached_houses', 'house_price_index_detached_houses', 'average_price_semidetached_houses', 'percentage_change_yearly_semidetached_houses', 'percentage_change_monthly_semidetached_houses', 'house_price_index_semidetached_houses', 'average_price_terraced_houses', 'percentage_change_yearly_terraced_houses', 'percentage_change_monthly_terraced_houses', 'house_price_index_terraced_houses', 'average_price_flats_and_maisonettes', 'percentage_change_yearly_flats_and_maisonettes', 'percentage_change_monthly_flats_and_maisonettes', 'house_price_index_flats_and_maisonettes', 'average_price_firsttime_buyers', 'percentage_change_yearly_firsttime_buyers', 'percentage_change_monthly_firsttime_buyers', 'house_price_index_firsttime_buyers', 'average_price_former_owneroccupiers', 'percentage_change_yearly_former_owneroccupiers', 'percentage_change_monthly_former_owneroccupiers', 'house_price_index_former_owneroccupiers', 'average_price_cash_purchases', 'percentage_change_yearly_cash_purchases', 'percentage_change_monthly_cash_purchases', 'house_price_index_cash_purchases', 'sales_volume_cash_purchases', 'average_price_mortgage_purchases', 'percentage_change_yearly_mortgage_purchases', 'percentage_change_monthly_mortgage_purchases', 'house_price_index_mortgage_purchases', 'sales_volume_mortgage_purchases', 'average_price_new_build', 'percentage_change_yearly_new_build', 'percentage_change_monthly_new_build', 'house_price_index_new_build', 'sales_volume_new_build', 'average_price_existing_properties', 'percentage_change_yearly_existing_properties', 'percentage_change_monthly_existing_properties', 'house_price_index_existing_properties', 'sales_volume_existing_properties', 'pivotable_date']

In [0]:
print(df.dtypes)
print("\nMissing values per column:\n")
print(df.isnull().sum())

name                                                object
uri                                                 object
region_gss_code                                     object
period                                              object
sales_volume                                       float64
reporting_period                                    object
average_price_all_property_types                     int64
percentage_change_yearly_all_property_types        float64
percentage_change_monthly_all_property_types       float64
house_price_index_all_property_types               float64
sales_volume_all_property_types                    float64
average_price_detached_houses                        int64
percentage_change_yearly_detached_houses           float64
percentage_change_monthly_detached_houses          float64
house_price_index_detached_houses                  float64
average_price_semidetached_houses                    int64
percentage_change_yearly_semidetached_houses       float64
percentage_change_monthly_semidetached_houses      float64
house_price_index_semidetached_houses              float64
average_price_terraced_houses                        int64
percentage_change_yearly_terraced_houses           float64
percentage_change_monthly_terraced_houses          float64
house_price_index_terraced_houses                  float64
average_price_flats_and_maisonettes                  int64
percentage_change_yearly_flats_and_maisonettes     float64
percentage_change_monthly_flats_and_maisonettes    float64
house_price_index_flats_and_maisonettes            float64
average_price_firsttime_buyers                       int64
percentage_change_yearly_firsttime_buyers          float64
percentage_change_monthly_firsttime_buyers         float64
house_price_index_firsttime_buyers                 float64
average_price_former_owneroccupiers                  int64
percentage_change_yearly_former_owneroccupiers     float64
percentage_change_monthly_former_owneroccupiers    float64
house_price_index_former_owneroccupiers            float64
average_price_cash_purchases                         int64
percentage_change_yearly_cash_purchases            float64
percentage_change_monthly_cash_purchases           float64
house_price_index_cash_purchases                   float64
sales_volume_cash_purchases                        float64
average_price_mortgage_purchases                     int64
percentage_change_yearly_mortgage_purchases        float64
percentage_change_monthly_mortgage_purchases       float64
house_price_index_mortgage_purchases               float64
sales_volume_mortgage_purchases                    float64
average_price_new_build                            float64
percentage_change_yearly_new_build                 float64
percentage_change_monthly_new_build                float64
house_price_index_new_build                        float64
sales_volume_new_build                             float64
average_price_existing_properties                  float64
percentage_change_yearly_existing_properties       float64
percentage_change_monthly_existing_properties      float64
house_price_index_existing_properties              float64
sales_volume_existing_properties                   float64
pivotable_date                                      object
dtype: object

Missing values per column:

name                                               0
uri                                                0
region_gss_code                                    0
period                                             0
sales_volume                                       2
reporting_period                                   0
average_price_all_property_types                   0
percentage_change_yearly_all_property_types        0
percentage_change_monthly_all_property_types       0
house_price_index_all_property_types               0
sales_volume_all_property_types                    2
average_price_detached_houses                      0
percentage_change_yearly_detached_houses           0
percentage_change_monthly_detached_houses          0
house_price_index_detached_houses                  0
average_price_semidetached_houses                  0
percentage_change_yearly_semidetached_houses       0
percentage_change_monthly_semidetached_houses      0
house_price_index_semidetached_houses              0
average_price_terraced_houses                      0
percentage_change_yearly_terraced_houses           0
percentage_change_monthly_terraced_houses          0
house_price_index_terraced_houses                  0
average_price_flats_and_maisonettes                0
percentage_change_yearly_flats_and_maisonettes     0
percentage_change_monthly_flats_and_maisonettes    0
house_price_index_flats_and_maisonettes            0
average_price_firsttime_buyers                     0
percentage_change_yearly_firsttime_buyers          0
percentage_change_monthly_firsttime_buyers         0
house_price_index_firsttime_buyers                 0
average_price_former_owneroccupiers                0
percentage_change_yearly_former_owneroccupiers     0
percentage_change_monthly_former_owneroccupiers    0
house_price_index_former_owneroccupiers            0
average_price_cash_purchases                       0
percentage_change_yearly_cash_purchases            0
percentage_change_monthly_cash_purchases           0
house_price_index_cash_purchases                   0
sales_volume_cash_purchases                        2
average_price_mortgage_purchases                   0
percentage_change_yearly_mortgage_purchases        0
percentage_change_monthly_mortgage_purchases       0
house_price_index_mortgage_purchases               0
sales_volume_mortgage_purchases                    2
average_price_new_build                            2
percentage_change_yearly_new_build                 2
percentage_change_monthly_new_build                2
house_price_index_new_build                        2
sales_volume_new_build                             2
average_price_existing_properties                  2
percentage_change_yearly_existing_properties       2
percentage_change_monthly_existing_properties      2
house_price_index_existing_properties              2
sales_volume_existing_properties                   2
pivotable_date                                     0
dtype: int64

In [0]:
df["pivotable_date"] = pd.to_datetime(df["pivotable_date"], errors="coerce")
df["period"] = pd.to_datetime(df["period"], errors="coerce")

print(df[["period", "pivotable_date"]].dtypes)
print(df[["period", "pivotable_date"]].head())

period            datetime64[ns]
pivotable_date    datetime64[ns]
dtype: object
      period pivotable_date
0 2015-01-01     2015-01-01
1 2015-02-01     2015-02-01
2 2015-03-01     2015-03-01
3 2015-04-01     2015-04-01
4 2015-05-01     2015-05-01

In [0]:
cleaned_file_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/housing_cleaned_test.csv"

df.to_csv(cleaned_file_path, index=False)

print("Cleaned file saved to:", cleaned_file_path)

Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/housing_cleaned_test.csv

In [0]:
null_summary = df.isnull().sum().reset_index()
null_summary.columns = ["column_name", "null_count"]
null_summary = null_summary[null_summary["null_count"] > 0].sort_values("null_count", ascending=False)

print(null_summary)

                                      column_name  null_count
4                                    sales_volume           2
10                sales_volume_all_property_types           2
39                    sales_volume_cash_purchases           2
44                sales_volume_mortgage_purchases           2
45                        average_price_new_build           2
46             percentage_change_yearly_new_build           2
47            percentage_change_monthly_new_build           2
48                    house_price_index_new_build           2
49                         sales_volume_new_build           2
50              average_price_existing_properties           2
51   percentage_change_yearly_existing_properties           2
52  percentage_change_monthly_existing_properties           2
53          house_price_index_existing_properties           2
54               sales_volume_existing_properties           2

In [0]:
df[df.isnull().any(axis=1)][["period", "name", "sales_volume", 
                             "sales_volume_all_property_types",
                             "sales_volume_cash_purchases",
                             "sales_volume_mortgage_purchases",
                             "average_price_new_build",
                             "average_price_existing_properties"]]

      period  ... average_price_existing_properties
131  2025-12  ...                               NaN
132  2026-01  ...                               NaN

[2 rows x 8 columns]

In [0]:
df["is_partial_record"] = df.isnull().any(axis=1)

df[["period", "name", "is_partial_record"]].tail(5)

      period           name  is_partial_record
128  2025-09  East Midlands              False
129  2025-10  East Midlands              False
130  2025-11  East Midlands              False
131  2025-12  East Midlands               True
132  2026-01  East Midlands               True

In [0]:
cleaned_file_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/housing_cleaned_test.csv"
df.to_csv(cleaned_file_path, index=False)

print("Updated cleaned file saved with partial-record flag.")

Updated cleaned file saved with partial-record flag.

In [0]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [0]:
df["uri"].head()

0    http://landregistry.data.gov.uk/id/region/east...
1    http://landregistry.data.gov.uk/id/region/east...
2    http://landregistry.data.gov.uk/id/region/east...
3    http://landregistry.data.gov.uk/id/region/east...
4    http://landregistry.data.gov.uk/id/region/east...
Name: uri, dtype: object

In [0]:
df["uri"].nunique()

1

In [0]:
df = df.drop(columns=["uri"])

print(df.columns.tolist())
print(df.shape)

['name', 'region_gss_code', 'period', 'sales_volume', 'reporting_period', 'average_price_all_property_types', 'percentage_change_yearly_all_property_types', 'percentage_change_monthly_all_property_types', 'house_price_index_all_property_types', 'sales_volume_all_property_types', 'average_price_detached_houses', 'percentage_change_yearly_detached_houses', 'percentage_change_monthly_detached_houses', 'house_price_index_detached_houses', 'average_price_semidetached_houses', 'percentage_change_yearly_semidetached_houses', 'percentage_change_monthly_semidetached_houses', 'house_price_index_semidetached_houses', 'average_price_terraced_houses', 'percentage_change_yearly_terraced_houses', 'percentage_change_monthly_terraced_houses', 'house_price_index_terraced_houses', 'average_price_flats_and_maisonettes', 'percentage_change_yearly_flats_and_maisonettes', 'percentage_change_monthly_flats_and_maisonettes', 'house_price_index_flats_and_maisonettes', 'average_price_firsttime_buyers', 'percentage_change_yearly_firsttime_buyers', 'percentage_change_monthly_firsttime_buyers', 'house_price_index_firsttime_buyers', 'average_price_former_owneroccupiers', 'percentage_change_yearly_former_owneroccupiers', 'percentage_change_monthly_former_owneroccupiers', 'house_price_index_former_owneroccupiers', 'average_price_cash_purchases', 'percentage_change_yearly_cash_purchases', 'percentage_change_monthly_cash_purchases', 'house_price_index_cash_purchases', 'sales_volume_cash_purchases', 'average_price_mortgage_purchases', 'percentage_change_yearly_mortgage_purchases', 'percentage_change_monthly_mortgage_purchases', 'house_price_index_mortgage_purchases', 'sales_volume_mortgage_purchases', 'average_price_new_build', 'percentage_change_yearly_new_build', 'percentage_change_monthly_new_build', 'house_price_index_new_build', 'sales_volume_new_build', 'average_price_existing_properties', 'percentage_change_yearly_existing_properties', 'percentage_change_monthly_existing_properties', 'house_price_index_existing_properties', 'sales_volume_existing_properties', 'pivotable_date', 'is_partial_record']
(133, 56)

In [0]:
cleaned_file_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/housing_cleaned_test.csv"
df.to_csv(cleaned_file_path, index=False)

print("Cleaned file updated without uri column.")

Cleaned file updated without uri column.

In [0]:
import pandas as pd
import re

def clean_column_name(col):
    col = col.strip().lower()
    col = re.sub(r"[^\w\s]", "", col)
    col = re.sub(r"\s+", "_", col)
    return col

def clean_housing_file(input_path, output_path):
    df = pd.read_csv(input_path)

    df.columns = [clean_column_name(col) for col in df.columns]

    if "period" in df.columns:
        df["period"] = pd.to_datetime(df["period"], errors="coerce")

    if "pivotable_date" in df.columns:
        df["pivotable_date"] = pd.to_datetime(df["pivotable_date"], errors="coerce")

    if "uri" in df.columns and df["uri"].nunique() == 1:
        df = df.drop(columns=["uri"])

    df["is_partial_record"] = df.isnull().any(axis=1)

    df.to_csv(output_path, index=False)
    print(f"Cleaned file saved to: {output_path}")

In [0]:
input_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/housing_processed_test.csv"
output_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/housing_cleaned_function_test.csv"

clean_housing_file(input_path, output_path)

Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/housing_cleaned_function_test.csv

In [0]:
import os
import pandas as pd
import re

base_path = "/Volumes/dbw_ukhousing_dev/default/housing_files"

def clean_column_name(col):
    col = col.strip().lower()
    col = re.sub(r"[^\w\s]", "", col)
    col = re.sub(r"\s+", "_", col)
    return col

def clean_housing_file(input_path, output_path):
    df = pd.read_csv(input_path)

    df.columns = [clean_column_name(col) for col in df.columns]

    if "period" in df.columns:
        df["period"] = pd.to_datetime(df["period"], errors="coerce")

    if "pivotable_date" in df.columns:
        df["pivotable_date"] = pd.to_datetime(df["pivotable_date"], errors="coerce")

    if "uri" in df.columns and df["uri"].nunique() == 1:
        df = df.drop(columns=["uri"])

    df["is_partial_record"] = df.isnull().any(axis=1)

    df.to_csv(output_path, index=False)
    print(f"Cleaned file saved to: {output_path}")

for file_name in os.listdir(base_path):
    if file_name.endswith(".csv") and "_cleaned" not in file_name:
        input_file = os.path.join(base_path, file_name)
        output_file = os.path.join(base_path, file_name.replace(".csv", "_cleaned.csv"))
        clean_housing_file(input_file, output_file)

Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/housing_processed_test_cleaned.csv
Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/ukhpi-east-midlands-from-2015-01-01-to-2026-01-01_cleaned.csv
Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/ukhpi-east-of-england-from-2015-01-01-to-2026-01-01_cleaned.csv
Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/ukhpi-london-from-2015-01-01-to-2026-01-01_cleaned.csv
Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/ukhpi-north-east-from-2015-01-01-to-2026-01-01_cleaned.csv
Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/ukhpi-north-west-from-2015-01-01-to-2026-01-01_cleaned.csv
Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/ukhpi-south-east-from-2015-01-01-to-2026-01-01_cleaned.csv
Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/ukhpi-south-west-from-2015-01-01-to-2026-01-01_cleaned.csv
Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/ukhpi-west-midlands-region-from-2015-01-01-to-2026-01-01_cleaned.csv
Cleaned file saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/ukhpi-yorkshire-and-the-humber-from-2015-01-01-to-2026-01-01_cleaned.csv

In [0]:
import os
import pandas as pd

base_path = "/Volumes/dbw_ukhousing_dev/default/housing_files"

cleaned_files = [
    f for f in os.listdir(base_path)
    if f.endswith("_cleaned.csv") and "housing_processed_test" not in f
]

df_list = []

for file_name in cleaned_files:
    file_path = os.path.join(base_path, file_name)
    df = pd.read_csv(file_path)
    df["source_file"] = file_name
    df_list.append(df)

master_df = pd.concat(df_list, ignore_index=True)

print("Number of cleaned files combined:", len(cleaned_files))
print("Master shape:", master_df.shape)
master_df.head()

Number of cleaned files combined: 10
Master shape: (1330, 57)

            name  ...                                        source_file
0  East Midlands  ...  ukhpi-east-midlands-from-2015-01-01-to-2026-01...
1  East Midlands  ...  ukhpi-east-midlands-from-2015-01-01-to-2026-01...
2  East Midlands  ...  ukhpi-east-midlands-from-2015-01-01-to-2026-01...
3  East Midlands  ...  ukhpi-east-midlands-from-2015-01-01-to-2026-01...
4  East Midlands  ...  ukhpi-east-midlands-from-2015-01-01-to-2026-01...

[5 rows x 57 columns]

In [0]:
import os
import pandas as pd

base_path = "/Volumes/dbw_ukhousing_dev/default/housing_files"

cleaned_files = [
    f for f in os.listdir(base_path)
    if f.endswith("_cleaned.csv")
    and "housing_processed_test" not in f
    and "housing_cleaned_test" not in f
    and "housing_cleaned_function_test" not in f
]

df_list = []

for file_name in cleaned_files:
    file_path = os.path.join(base_path, file_name)
    df = pd.read_csv(file_path)
    df["source_file"] = file_name
    df_list.append(df)

master_df = pd.concat(df_list, ignore_index=True)

print("Number of cleaned files combined:", len(cleaned_files))
print("Master shape:", master_df.shape)

Number of cleaned files combined: 9
Master shape: (1197, 57)

In [0]:
master_output_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv"

master_df.to_csv(master_output_path, index=False)

print("Master dataset saved to:", master_output_path)

Master dataset saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv

In [0]:
import pandas as pd

master_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv"
master_df = pd.read_csv(master_path)

print(master_df.shape)
print(master_df.columns.tolist())

(1197, 56)
['name', 'region_gss_code', 'period', 'sales_volume', 'reporting_period', 'average_price_all_property_types', 'percentage_change_yearly_all_property_types', 'percentage_change_monthly_all_property_types', 'house_price_index_all_property_types', 'sales_volume_all_property_types', 'average_price_detached_houses', 'percentage_change_yearly_detached_houses', 'percentage_change_monthly_detached_houses', 'house_price_index_detached_houses', 'average_price_semidetached_houses', 'percentage_change_yearly_semidetached_houses', 'percentage_change_monthly_semidetached_houses', 'house_price_index_semidetached_houses', 'average_price_terraced_houses', 'percentage_change_yearly_terraced_houses', 'percentage_change_monthly_terraced_houses', 'house_price_index_terraced_houses', 'average_price_flats_and_maisonettes', 'percentage_change_yearly_flats_and_maisonettes', 'percentage_change_monthly_flats_and_maisonettes', 'house_price_index_flats_and_maisonettes', 'average_price_firsttime_buyers', 'percentage_change_yearly_firsttime_buyers', 'percentage_change_monthly_firsttime_buyers', 'house_price_index_firsttime_buyers', 'average_price_former_owneroccupiers', 'percentage_change_yearly_former_owneroccupiers', 'percentage_change_monthly_former_owneroccupiers', 'house_price_index_former_owneroccupiers', 'average_price_cash_purchases', 'percentage_change_yearly_cash_purchases', 'percentage_change_monthly_cash_purchases', 'house_price_index_cash_purchases', 'sales_volume_cash_purchases', 'average_price_mortgage_purchases', 'percentage_change_yearly_mortgage_purchases', 'percentage_change_monthly_mortgage_purchases', 'house_price_index_mortgage_purchases', 'sales_volume_mortgage_purchases', 'average_price_new_build', 'percentage_change_yearly_new_build', 'percentage_change_monthly_new_build', 'house_price_index_new_build', 'sales_volume_new_build', 'average_price_existing_properties', 'percentage_change_yearly_existing_properties', 'percentage_change_monthly_existing_properties', 'house_price_index_existing_properties', 'sales_volume_existing_properties', 'is_partial_record', 'source_file']

In [0]:
master_df = master_df.drop(columns=["pivotable_date"])

print(master_df.shape)
print(master_df[["period"]].head())

(1197, 56)
       period
0  2015-01-01
1  2015-02-01
2  2015-03-01
3  2015-04-01
4  2015-05-01

In [0]:
print("Exact duplicate rows:", master_df.duplicated().sum())

Exact duplicate rows: 0

In [0]:
master_df.to_csv(master_path, index=False)
print("Master dataset updated without pivotable_date.")

Master dataset updated without pivotable_date.

In [0]:
master_df = master_df.drop(columns=["reporting_period"])

print(master_df.shape)
print(master_df.columns.tolist())

(1197, 55)
['name', 'region_gss_code', 'period', 'sales_volume', 'average_price_all_property_types', 'percentage_change_yearly_all_property_types', 'percentage_change_monthly_all_property_types', 'house_price_index_all_property_types', 'sales_volume_all_property_types', 'average_price_detached_houses', 'percentage_change_yearly_detached_houses', 'percentage_change_monthly_detached_houses', 'house_price_index_detached_houses', 'average_price_semidetached_houses', 'percentage_change_yearly_semidetached_houses', 'percentage_change_monthly_semidetached_houses', 'house_price_index_semidetached_houses', 'average_price_terraced_houses', 'percentage_change_yearly_terraced_houses', 'percentage_change_monthly_terraced_houses', 'house_price_index_terraced_houses', 'average_price_flats_and_maisonettes', 'percentage_change_yearly_flats_and_maisonettes', 'percentage_change_monthly_flats_and_maisonettes', 'house_price_index_flats_and_maisonettes', 'average_price_firsttime_buyers', 'percentage_change_yearly_firsttime_buyers', 'percentage_change_monthly_firsttime_buyers', 'house_price_index_firsttime_buyers', 'average_price_former_owneroccupiers', 'percentage_change_yearly_former_owneroccupiers', 'percentage_change_monthly_former_owneroccupiers', 'house_price_index_former_owneroccupiers', 'average_price_cash_purchases', 'percentage_change_yearly_cash_purchases', 'percentage_change_monthly_cash_purchases', 'house_price_index_cash_purchases', 'sales_volume_cash_purchases', 'average_price_mortgage_purchases', 'percentage_change_yearly_mortgage_purchases', 'percentage_change_monthly_mortgage_purchases', 'house_price_index_mortgage_purchases', 'sales_volume_mortgage_purchases', 'average_price_new_build', 'percentage_change_yearly_new_build', 'percentage_change_monthly_new_build', 'house_price_index_new_build', 'sales_volume_new_build', 'average_price_existing_properties', 'percentage_change_yearly_existing_properties', 'percentage_change_monthly_existing_properties', 'house_price_index_existing_properties', 'sales_volume_existing_properties', 'is_partial_record', 'source_file']

In [0]:
master_df.to_csv("/tmp/uk_housing_master_dataset.csv", index=False)
print("Saved to /tmp/uk_housing_master_dataset.csv")

Saved to /tmp/uk_housing_master_dataset.csv

In [0]:
import pandas as pd

master_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv"
master_df = pd.read_csv(master_path)

print(master_df.shape)

(1197, 56)

In [0]:
if "reporting_period" in master_df.columns:
    master_df["reporting_period"] = (
        master_df["reporting_period"]
        .astype("string")
        .str.strip()
        .str.lower()
        .replace({
            "month": "monthly",
            "monthly ": "monthly",
            " monthly": "monthly"
        })
    )

print(master_df["reporting_period"].value_counts(dropna=False))

reporting_period
monthly    1197
Name: count, dtype: Int64

In [0]:
master_df.to_csv(master_path, index=False)
print("Master dataset updated.")

Master dataset updated.

In [0]:
import pandas as pd

master_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv"

master_df = pd.read_csv(master_path)
print("Before:", master_df.shape)
print(master_df.columns.tolist())

Before: (1197, 56)
['name', 'region_gss_code', 'period', 'sales_volume', 'reporting_period', 'average_price_all_property_types', 'percentage_change_yearly_all_property_types', 'percentage_change_monthly_all_property_types', 'house_price_index_all_property_types', 'sales_volume_all_property_types', 'average_price_detached_houses', 'percentage_change_yearly_detached_houses', 'percentage_change_monthly_detached_houses', 'house_price_index_detached_houses', 'average_price_semidetached_houses', 'percentage_change_yearly_semidetached_houses', 'percentage_change_monthly_semidetached_houses', 'house_price_index_semidetached_houses', 'average_price_terraced_houses', 'percentage_change_yearly_terraced_houses', 'percentage_change_monthly_terraced_houses', 'house_price_index_terraced_houses', 'average_price_flats_and_maisonettes', 'percentage_change_yearly_flats_and_maisonettes', 'percentage_change_monthly_flats_and_maisonettes', 'house_price_index_flats_and_maisonettes', 'average_price_firsttime_buyers', 'percentage_change_yearly_firsttime_buyers', 'percentage_change_monthly_firsttime_buyers', 'house_price_index_firsttime_buyers', 'average_price_former_owneroccupiers', 'percentage_change_yearly_former_owneroccupiers', 'percentage_change_monthly_former_owneroccupiers', 'house_price_index_former_owneroccupiers', 'average_price_cash_purchases', 'percentage_change_yearly_cash_purchases', 'percentage_change_monthly_cash_purchases', 'house_price_index_cash_purchases', 'sales_volume_cash_purchases', 'average_price_mortgage_purchases', 'percentage_change_yearly_mortgage_purchases', 'percentage_change_monthly_mortgage_purchases', 'house_price_index_mortgage_purchases', 'sales_volume_mortgage_purchases', 'average_price_new_build', 'percentage_change_yearly_new_build', 'percentage_change_monthly_new_build', 'house_price_index_new_build', 'sales_volume_new_build', 'average_price_existing_properties', 'percentage_change_yearly_existing_properties', 'percentage_change_monthly_existing_properties', 'house_price_index_existing_properties', 'sales_volume_existing_properties', 'is_partial_record', 'source_file']

In [0]:
if "reporting_period" in master_df.columns:
    master_df = master_df.drop(columns=["reporting_period"])

print("After:", master_df.shape)
print(master_df.columns.tolist())

After: (1197, 55)
['name', 'region_gss_code', 'period', 'sales_volume', 'average_price_all_property_types', 'percentage_change_yearly_all_property_types', 'percentage_change_monthly_all_property_types', 'house_price_index_all_property_types', 'sales_volume_all_property_types', 'average_price_detached_houses', 'percentage_change_yearly_detached_houses', 'percentage_change_monthly_detached_houses', 'house_price_index_detached_houses', 'average_price_semidetached_houses', 'percentage_change_yearly_semidetached_houses', 'percentage_change_monthly_semidetached_houses', 'house_price_index_semidetached_houses', 'average_price_terraced_houses', 'percentage_change_yearly_terraced_houses', 'percentage_change_monthly_terraced_houses', 'house_price_index_terraced_houses', 'average_price_flats_and_maisonettes', 'percentage_change_yearly_flats_and_maisonettes', 'percentage_change_monthly_flats_and_maisonettes', 'house_price_index_flats_and_maisonettes', 'average_price_firsttime_buyers', 'percentage_change_yearly_firsttime_buyers', 'percentage_change_monthly_firsttime_buyers', 'house_price_index_firsttime_buyers', 'average_price_former_owneroccupiers', 'percentage_change_yearly_former_owneroccupiers', 'percentage_change_monthly_former_owneroccupiers', 'house_price_index_former_owneroccupiers', 'average_price_cash_purchases', 'percentage_change_yearly_cash_purchases', 'percentage_change_monthly_cash_purchases', 'house_price_index_cash_purchases', 'sales_volume_cash_purchases', 'average_price_mortgage_purchases', 'percentage_change_yearly_mortgage_purchases', 'percentage_change_monthly_mortgage_purchases', 'house_price_index_mortgage_purchases', 'sales_volume_mortgage_purchases', 'average_price_new_build', 'percentage_change_yearly_new_build', 'percentage_change_monthly_new_build', 'house_price_index_new_build', 'sales_volume_new_build', 'average_price_existing_properties', 'percentage_change_yearly_existing_properties', 'percentage_change_monthly_existing_properties', 'house_price_index_existing_properties', 'sales_volume_existing_properties', 'is_partial_record', 'source_file']

In [0]:
import pandas as pd

master_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv"

master_df = pd.read_csv(master_path)

cols_to_drop = [c for c in ["reporting_period", "source_file", "pivotable_date"] if c in master_df.columns]
master_df = master_df.drop(columns=cols_to_drop)

master_df.to_csv(master_path, index=False)

check_df = pd.read_csv(master_path)
print("Dropped:", cols_to_drop)
print("Reloaded shape:", check_df.shape)
print(check_df.columns.tolist())

Dropped: ['reporting_period', 'source_file']
Reloaded shape: (1197, 54)
['name', 'region_gss_code', 'period', 'sales_volume', 'average_price_all_property_types', 'percentage_change_yearly_all_property_types', 'percentage_change_monthly_all_property_types', 'house_price_index_all_property_types', 'sales_volume_all_property_types', 'average_price_detached_houses', 'percentage_change_yearly_detached_houses', 'percentage_change_monthly_detached_houses', 'house_price_index_detached_houses', 'average_price_semidetached_houses', 'percentage_change_yearly_semidetached_houses', 'percentage_change_monthly_semidetached_houses', 'house_price_index_semidetached_houses', 'average_price_terraced_houses', 'percentage_change_yearly_terraced_houses', 'percentage_change_monthly_terraced_houses', 'house_price_index_terraced_houses', 'average_price_flats_and_maisonettes', 'percentage_change_yearly_flats_and_maisonettes', 'percentage_change_monthly_flats_and_maisonettes', 'house_price_index_flats_and_maisonettes', 'average_price_firsttime_buyers', 'percentage_change_yearly_firsttime_buyers', 'percentage_change_monthly_firsttime_buyers', 'house_price_index_firsttime_buyers', 'average_price_former_owneroccupiers', 'percentage_change_yearly_former_owneroccupiers', 'percentage_change_monthly_former_owneroccupiers', 'house_price_index_former_owneroccupiers', 'average_price_cash_purchases', 'percentage_change_yearly_cash_purchases', 'percentage_change_monthly_cash_purchases', 'house_price_index_cash_purchases', 'sales_volume_cash_purchases', 'average_price_mortgage_purchases', 'percentage_change_yearly_mortgage_purchases', 'percentage_change_monthly_mortgage_purchases', 'house_price_index_mortgage_purchases', 'sales_volume_mortgage_purchases', 'average_price_new_build', 'percentage_change_yearly_new_build', 'percentage_change_monthly_new_build', 'house_price_index_new_build', 'sales_volume_new_build', 'average_price_existing_properties', 'percentage_change_yearly_existing_properties', 'percentage_change_monthly_existing_properties', 'house_price_index_existing_properties', 'sales_volume_existing_properties', 'is_partial_record']

In [0]:
master_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv"

master_df.to_csv(master_path, index=False)

print("Saved to:", master_path)

Saved to: /Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv

In [0]:
import pandas as pd

master_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv"

master_df = pd.read_csv(master_path)

if "sales_volume" in master_df.columns:
    master_df = master_df.drop(columns=["sales_volume"])

master_df.to_csv(master_path, index=False)

check_df = pd.read_csv(master_path)

print("Updated shape:", check_df.shape)
print("sales_volume" in check_df.columns)
print("sales_volume_all_property_types" in check_df.columns)
print(check_df.columns.tolist())

Updated shape: (1197, 53)
False
True
['name', 'region_gss_code', 'period', 'average_price_all_property_types', 'percentage_change_yearly_all_property_types', 'percentage_change_monthly_all_property_types', 'house_price_index_all_property_types', 'sales_volume_all_property_types', 'average_price_detached_houses', 'percentage_change_yearly_detached_houses', 'percentage_change_monthly_detached_houses', 'house_price_index_detached_houses', 'average_price_semidetached_houses', 'percentage_change_yearly_semidetached_houses', 'percentage_change_monthly_semidetached_houses', 'house_price_index_semidetached_houses', 'average_price_terraced_houses', 'percentage_change_yearly_terraced_houses', 'percentage_change_monthly_terraced_houses', 'house_price_index_terraced_houses', 'average_price_flats_and_maisonettes', 'percentage_change_yearly_flats_and_maisonettes', 'percentage_change_monthly_flats_and_maisonettes', 'house_price_index_flats_and_maisonettes', 'average_price_firsttime_buyers', 'percentage_change_yearly_firsttime_buyers', 'percentage_change_monthly_firsttime_buyers', 'house_price_index_firsttime_buyers', 'average_price_former_owneroccupiers', 'percentage_change_yearly_former_owneroccupiers', 'percentage_change_monthly_former_owneroccupiers', 'house_price_index_former_owneroccupiers', 'average_price_cash_purchases', 'percentage_change_yearly_cash_purchases', 'percentage_change_monthly_cash_purchases', 'house_price_index_cash_purchases', 'sales_volume_cash_purchases', 'average_price_mortgage_purchases', 'percentage_change_yearly_mortgage_purchases', 'percentage_change_monthly_mortgage_purchases', 'house_price_index_mortgage_purchases', 'sales_volume_mortgage_purchases', 'average_price_new_build', 'percentage_change_yearly_new_build', 'percentage_change_monthly_new_build', 'house_price_index_new_build', 'sales_volume_new_build', 'average_price_existing_properties', 'percentage_change_yearly_existing_properties', 'percentage_change_monthly_existing_properties', 'house_price_index_existing_properties', 'sales_volume_existing_properties', 'is_partial_record']

In [0]:
import os

base_path = "/Volumes/dbw_ukhousing_dev/default/housing_files"
for f in os.listdir(base_path):
    if "uk_housing_master_dataset" in f:
        print(f)

uk_housing_master_dataset.csv
uk_housing_master_dataset_final.csv

In [0]:
%pip install azure-storage-blob==12.24.0

Collecting azure-storage-blob==12.24.0
  Downloading azure_storage_blob-12.24.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: azure-core>=1.30.0 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-blob==12.24.0) (1.37.0)
Requirement already satisfied: cryptography>=2.1.4 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-blob==12.24.0) (44.0.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-blob==12.24.0) (4.12.2)
Requirement already satisfied: isodate>=0.6.1 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-blob==12.24.0) (0.7.2)
Requirement already satisfied: requests>=2.21.0 in /databricks/python3/lib/python3.12/site-packages (from azure-core>=1.30.0->azure-storage-blob==12.24.0) (2.32.3)
Requirement already satisfied: cffi>=1.12 in /databricks/python3/lib/python3.12/site-packages (from cryptography>=2.1.4->azure-storage-blob==12.24.0) (1.17.1)
Requirement already satisfied: pycparser in /databricks/python3/lib/python3.12/site-packages (from cffi>=1.12->cryptography>=2.1.4->azure-storage-blob==12.24.0) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob==12.24.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob==12.24.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob==12.24.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob==12.24.0) (2025.4.26)
Downloading azure_storage_blob-12.24.0-py3-none-any.whl (408 kB)
Installing collected packages: azure-storage-blob
  Attempting uninstall: azure-storage-blob
    Found existing installation: azure-storage-blob 12.28.0
    Not uninstalling azure-storage-blob at /databricks/python3/lib/python3.12/site-packages, outside environment /local_disk0/.ephemeral_nfs/envs/pythonEnv-fa0e24eb-751b-4291-81e7-0cf686272d28
    Can't uninstall 'azure-storage-blob'. No files were found to uninstall.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
azure-storage-file-datalake 12.22.0 requires azure-storage-blob>=12.27.0, but you have azure-storage-blob 12.24.0 which is incompatible.
Successfully installed azure-storage-blob-12.24.0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
%pip install azure-storage-blob==12.28.0

Collecting azure-storage-blob==12.28.0
  Downloading azure_storage_blob-12.28.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: azure-core>=1.30.0 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-blob==12.28.0) (1.37.0)
Requirement already satisfied: cryptography>=2.1.4 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-blob==12.28.0) (44.0.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-blob==12.28.0) (4.12.2)
Requirement already satisfied: isodate>=0.6.1 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-blob==12.28.0) (0.7.2)
Requirement already satisfied: requests>=2.21.0 in /databricks/python3/lib/python3.12/site-packages (from azure-core>=1.30.0->azure-storage-blob==12.28.0) (2.32.3)
Requirement already satisfied: cffi>=1.12 in /databricks/python3/lib/python3.12/site-packages (from cryptography>=2.1.4->azure-storage-blob==12.28.0) (1.17.1)
Requirement already satisfied: pycparser in /databricks/python3/lib/python3.12/site-packages (from cffi>=1.12->cryptography>=2.1.4->azure-storage-blob==12.28.0) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob==12.28.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob==12.28.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob==12.28.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.12/site-packages (from requests>=2.21.0->azure-core>=1.30.0->azure-storage-blob==12.28.0) (2025.4.26)
Downloading azure_storage_blob-12.28.0-py3-none-any.whl (431 kB)
Installing collected packages: azure-storage-blob
  Attempting uninstall: azure-storage-blob
    Found existing installation: azure-storage-blob 12.24.0
    Uninstalling azure-storage-blob-12.24.0:
      Successfully uninstalled azure-storage-blob-12.24.0
Successfully installed azure-storage-blob-12.28.0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
dbutils.library.restartPython()

In [0]:
from azure.storage.blob import BlobClient

local_file_path = "/Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv"
account_name = "stukhousingdev01"
container_name = "curated"
blob_name = "uk_housing_master_dataset_curated.csv"
sas_token = "sp=rcw&st=2026-04-10T10:06:50Z&se=2026-04-10T18:21:50Z&spr=https&sv=2025-11-05&sr=c&sig=PdH1MCrZ9yu5G8ReCruhkY2VJZA%2FUshvDWUJDTkvB0g%3D"

blob_url = f"https://{account_name}.blob.core.windows.net/{container_name}/{blob_name}?{sas_token}"

with open(local_file_path, "rb") as data:
    blob_client = BlobClient.from_blob_url(blob_url)
    blob_client.upload_blob(data, overwrite=True)

print("Upload completed:", blob_name)

Upload completed: uk_housing_master_dataset_curated.csv

In [0]:
df = spark.read.format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .load("/Volumes/dbw_ukhousing_dev/default/housing_files/uk_housing_master_dataset.csv")

print("Rows:", df.count())
print("Columns:", len(df.columns))

for col in df.columns:
    print(col)

Rows: 1197
Columns: 53
name
region_gss_code
period
average_price_all_property_types
percentage_change_yearly_all_property_types
percentage_change_monthly_all_property_types
house_price_index_all_property_types
sales_volume_all_property_types
average_price_detached_houses
percentage_change_yearly_detached_houses
percentage_change_monthly_detached_houses
house_price_index_detached_houses
average_price_semidetached_houses
percentage_change_yearly_semidetached_houses
percentage_change_monthly_semidetached_houses
house_price_index_semidetached_houses
average_price_terraced_houses
percentage_change_yearly_terraced_houses
percentage_change_monthly_terraced_houses
house_price_index_terraced_houses
average_price_flats_and_maisonettes
percentage_change_yearly_flats_and_maisonettes
percentage_change_monthly_flats_and_maisonettes
house_price_index_flats_and_maisonettes
average_price_firsttime_buyers
percentage_change_yearly_firsttime_buyers
percentage_change_monthly_firsttime_buyers
house_price_index_firsttime_buyers
average_price_former_owneroccupiers
percentage_change_yearly_former_owneroccupiers
percentage_change_monthly_former_owneroccupiers
house_price_index_former_owneroccupiers
average_price_cash_purchases
percentage_change_yearly_cash_purchases
percentage_change_monthly_cash_purchases
house_price_index_cash_purchases
sales_volume_cash_purchases
average_price_mortgage_purchases
percentage_change_yearly_mortgage_purchases
percentage_change_monthly_mortgage_purchases
house_price_index_mortgage_purchases
sales_volume_mortgage_purchases
average_price_new_build
percentage_change_yearly_new_build
percentage_change_monthly_new_build
house_price_index_new_build
sales_volume_new_build
average_price_existing_properties
percentage_change_yearly_existing_properties
percentage_change_monthly_existing_properties
house_price_index_existing_properties
sales_volume_existing_properties
is_partial_record